[build]
  publish = "public"
  command = "yarn build"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/:splat?lang='en'"
  status = 302
  conditions = {Language = ["en"], Country = ["US", "GB"]}

[[redirects]]
  from = "/*"
  to = "/:splat?lang='pt-BR'"
  status = 302
  conditions = {Language = ["pt"], Country = ["BR", "PT"]}