[build]
  publish = "public"
  command = "yarn build"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/?lang=\"pt-BR\""
  status = 200
  conditions = {Country = ["br", "pt"]}

[[redirects]]
  from = "/*"
  to = "/?lang=\"en\""
  status = 200
  conditions = {Country = ["us", "gb"]}
