[build]
  publish = "public"
  command = "yarn build"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/:splat?lang=\"pt-BR\""
  status = 302
  conditions = {Country = ["br", "pt"]}

[[redirects]]
  from = "/*"
  to = "/:splat?lang=\"en\""
  status = 302
  conditions = {Country = ["us", "gb"]}
