[build]
  publish = "public"
  command = "yarn build"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/:splat?lang=\"en\""
  status = 200
  conditions = {Country = ["us", "gb"]}