[build]
  publish = "public"
  command = "yarn build"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/*"
  to = "/pt-BR/:splat"
  status = 302
  conditions = {Country = ["br", "pt"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  conditions = {Country = ["us", "gb"]}
